const elements = [
    { number: 1, symbol: 'H', name: 'Hydrogen', atomicWeight: 1.008 },
    { number: 2, symbol: 'He', name: 'Helium', atomicWeight: 4.0026 },
    { number: 3, symbol: 'Li', name: 'Lithium', atomicWeight: 6.94 },
    { number: 4, symbol: 'Be', name: 'Beryllium', atomicWeight: 9.0122 },
    { number: 5, symbol: 'B', name: 'Boron', atomicWeight: 10.81 },
    { number: 6, symbol: 'C', name: 'Carbon', atomicWeight: 12.011 },
    { number: 7, symbol: 'N', name: 'Nitrogen', atomicWeight: 14.007 },
    { number: 8, symbol: 'O', name: 'Oxygen', atomicWeight: 15.999 },
    { number: 9, symbol: 'F', name: 'Fluorine', atomicWeight: 18.998 },
    { number: 10, symbol: 'Ne', name: 'Neon', atomicWeight: 20.180 },
    { number: 11, symbol: 'Na', name: 'Sodium', atomicWeight: 22.990 },
    { number: 12, symbol: 'Mg', name: 'Magnesium', atomicWeight: 24.305 },
    { number: 13, symbol: 'Al', name: 'Aluminum', atomicWeight: 26.982 },
    { number: 14, symbol: 'Si', name: 'Silicon', atomicWeight: 28.085 },
    { number: 15, symbol: 'P', name: 'Phosphorus', atomicWeight: 30.974 },
    { number: 16, symbol: 'S', name: 'Sulfur', atomicWeight: 32.06 },
    { number: 17, symbol: 'Cl', name: 'Chlorine', atomicWeight: 35.45 },
    { number: 18, symbol: 'Ar', name: 'Argon', atomicWeight: 39.948 },
    { number: 19, symbol: 'K', name: 'Potassium', atomicWeight: 39.098 },
    { number: 20, symbol: 'Ca', name: 'Calcium', atomicWeight: 40.078 },
    { number: 21, symbol: 'Sc', name: 'Scandium', atomicWeight: 44.956 },
    { number: 22, symbol: 'Ti', name: 'Titanium', atomicWeight: 47.867 },
    { number: 23, symbol: 'V', name: 'Vanadium', atomicWeight: 50.941 },
    { number: 24, symbol: 'Cr', name: 'Chromium', atomicWeight: 51.996 },
    { number: 25, symbol: 'Mn', name: 'Manganese', atomicWeight: 54.938 },
    { number: 26, symbol: 'Fe', name: 'Iron', atomicWeight: 55.845 },
    { number: 27, symbol: 'Co', name: 'Cobalt', atomicWeight: 58.933 },
    { number: 28, symbol: 'Ni', name: 'Nickel', atomicWeight: 58.693 },
    { number: 29, symbol: 'Cu', name: 'Copper', atomicWeight: 63.546 },
    { number: 30, symbol: 'Zn', name: 'Zinc', atomicWeight: 65.38 },
    { number: 31, symbol: 'Ga', name: 'Gallium', atomicWeight: 69.723 },
    { number: 32, symbol: 'Ge', name: 'Germanium', atomicWeight: 72.630 },
    { number: 33, symbol: 'As', name: 'Arsenic', atomicWeight: 74.922 },
    { number: 34, symbol: 'Se', name: 'Selenium', atomicWeight: 78.971 },
    { number: 35, symbol: 'Br', name: 'Bromine', atomicWeight: 79.904 },
    { number: 36, symbol: 'Kr', name: 'Krypton', atomicWeight: 83.798 },
    { number: 37, symbol: 'Rb', name: 'Rubidium', atomicWeight: 85.468 },
    { number: 38, symbol: 'Sr', name: 'Strontium', atomicWeight: 87.62 },
    { number: 39, symbol: 'Y', name: 'Yttrium', atomicWeight: 88.906 },
    { number: 40, symbol: 'Zr', name: 'Zirconium', atomicWeight: 91.224 },
    { number: 41, symbol: 'Nb', name: 'Niobium', atomicWeight: 92.906 },
    { number: 42, symbol: 'Mo', name: 'Molybdenum', atomicWeight: 95.95 },
    { number: 43, symbol: 'Tc', name: 'Technetium', atomicWeight: 98 },
    { number: 44, symbol: 'Ru', name: 'Ruthenium', atomicWeight: 101.07 },
    { number: 45, symbol: 'Rh', name: 'Rhodium', atomicWeight: 102.91 },
    { number: 46, symbol: 'Pd', name: 'Palladium', atomicWeight: 106.42 },
    { number: 47, symbol: 'Ag', name: 'Silver', atomicWeight: 107.87 },
    { number: 48, symbol: 'Cd', name: 'Cadmium', atomicWeight: 112.41 },
    { number: 49, symbol: 'In', name: 'Indium', atomicWeight: 114.82 },
    { number: 50, symbol: 'Sn', name: 'Tin', atomicWeight: 118.71 },
    { number: 51, symbol: 'Sb', name: 'Antimony', atomicWeight: 121.76 },
    { number: 52, symbol: 'Te', name: 'Tellurium', atomicWeight: 127.60 },
    { number: 53, symbol: 'I', name: 'Iodine', atomicWeight: 126.90 },
    { number: 54, symbol: 'Xe', name: 'Xenon', atomicWeight: 131.29 },
    { number: 55, symbol: 'Cs', name: 'Cesium', atomicWeight: 132.91 },
    { number: 56, symbol: 'Ba', name: 'Barium', atomicWeight: 137.33 },
    { number: 57, symbol: 'La', name: 'Lanthanum', atomicWeight: 138.91 },
    { number: 58, symbol: 'Ce', name: 'Cerium', atomicWeight: 140.12 },
    { number: 59, symbol: 'Pr', name: 'Praseodymium', atomicWeight: 140.91 },
    { number: 60, symbol: 'Nd', name: 'Neodymium', atomicWeight: 144.24 },
    { number: 61, symbol: 'Pm', name: 'Promethium', atomicWeight: 145 },
    { number: 62, symbol: 'Sm', name: 'Samarium', atomicWeight: 150.36 },
    { number: 63, symbol: 'Eu', name: 'Europium', atomicWeight: 151.96 },
    { number: 64, symbol: 'Gd', name: 'Gadolinium', atomicWeight: 157.25 },
    { number: 65, symbol: 'Tb', name: 'Terbium', atomicWeight: 158.93 },
    { number: 66, symbol: 'Dy', name: 'Dysprosium', atomicWeight: 162.50 },
    { number: 67, symbol: 'Ho', name: 'Holmium', atomicWeight: 164.93 },
    { number: 68, symbol: 'Er', name: 'Erbium', atomicWeight: 167.26 },
    { number: 69, symbol: 'Tm', name: 'Thulium', atomicWeight: 168.93 },
    { number: 70, symbol: 'Yb', name: 'Ytterbium', atomicWeight: 173.04 },
    { number: 71, symbol: 'Lu', name: 'Lutetium', atomicWeight: 174.97 },
    { number: 72, symbol: 'Hf', name: 'Hafnium', atomicWeight: 178.49 },
    { number: 73, symbol: 'Ta', name: 'Tantalum', atomicWeight: 180.95 },
    { number: 74, symbol: 'W', name: 'Tungsten', atomicWeight: 183.84 },
    { number: 75, symbol: 'Re', name: 'Rhenium', atomicWeight: 186.21 },
    { number: 76, symbol: 'Os', name: 'Osmium', atomicWeight: 190.23 },
    { number: 77, symbol: 'Ir', name: 'Iridium', atomicWeight: 192.22 },
    { number: 78, symbol: 'Pt', name: 'Platinum', atomicWeight: 195.08 },
    { number: 79, symbol: 'Au', name: 'Gold', atomicWeight: 196.97 },
    { number: 80, symbol: 'Hg', name: 'Mercury', atomicWeight: 200.59 },
    { number: 81, symbol: 'Tl', name: 'Thallium', atomicWeight: 204.38 },
    { number: 82, symbol: 'Pb', name: 'Lead', atomicWeight: 207.2 },
    { number: 83, symbol: 'Bi', name: 'Bismuth', atomicWeight: 208.98 },
    { number: 84, symbol: 'Po', name: 'Polonium', atomicWeight: 209 },
    { number: 85, symbol: 'At', name: 'Astatine', atomicWeight: 210 },
    { number: 86, symbol: 'Rn', name: 'Radon', atomicWeight: 222 },
    { number: 87, symbol: 'Fr', name: 'Francium', atomicWeight: 223 },
    { number: 88, symbol: 'Ra', name: 'Radium', atomicWeight: 226 },
    { number: 89, symbol: 'Ac', name: 'Actinium', atomicWeight: 227 },
    { number: 90, symbol: 'Th', name: 'Thorium', atomicWeight: 232.04 },
    { number: 91, symbol: 'Pa', name: 'Protactinium', atomicWeight: 231.04 },
    { number: 92, symbol: 'U', name: 'Uranium', atomicWeight: 238.03 },
    { number: 93, symbol: 'Np', name: 'Neptunium', atomicWeight: 237 },
    { number: 94, symbol: 'Pu', name: 'Plutonium', atomicWeight: 244 },
    { number: 95, symbol: 'Am', name: 'Americium', atomicWeight: 243 },
    { number: 96, symbol: 'Cm', name: 'Curium', atomicWeight: 247 },
    { number: 97, symbol: 'Bk', name: 'Berkelium', atomicWeight: 247 },
    { number: 98, symbol: 'Cf', name: 'Californium', atomicWeight: 251 },
    { number: 99, symbol: 'Es', name: 'Einsteinium', atomicWeight: 252 },
    { number: 100, symbol: 'Fm', name: 'Fermium', atomicWeight: 257 },
    { number: 101, symbol: 'Md', name: 'Mendelevium', atomicWeight: 258 },
    { number: 102, symbol: 'No', name: 'Nobelium', atomicWeight: 259 },
    { number: 103, symbol: 'Lr', name: 'Lawrencium', atomicWeight: 266 },
    { number: 104, symbol: 'Rf', name: 'Rutherfordium', atomicWeight: 267 },
    { number: 105, symbol: 'Db', name: 'Dubnium', atomicWeight: 268 },
    { number: 106, symbol: 'Sg', name: 'Seaborgium', atomicWeight: 271 },
    { number: 107, symbol: 'Bh', name: 'Bohrium', atomicWeight: 270 },
    { number: 108, symbol: 'Hs', name: 'Hassium', atomicWeight: 277 },
    { number: 109, symbol: 'Mt', name: 'Meitnerium', atomicWeight: 278 },
    { number: 110, symbol: 'Ds', name: 'Darmstadtium', atomicWeight: 281 },
    { number: 111, symbol: 'Rg', name: 'Roentgenium', atomicWeight: 282 },
    { number: 112, symbol: 'Cn', name: 'Copernicium', atomicWeight: 285 },
    { number: 113, symbol: 'Nh', name: 'Nihonium', atomicWeight: 286 },
    { number: 114, symbol: 'Fl', name: 'Flerovium', atomicWeight: 289 },
    { number: 115, symbol: 'Mc', name: 'Moscovium', atomicWeight: 288 },
    { number: 116, symbol: 'Lv', name: 'Livermorium', atomicWeight: 293 },
    { number: 117, symbol: 'Ts', name: 'Tennessine', atomicWeight: 294 },
    { number: 118, symbol: 'Og', name: 'Oganesson', atomicWeight: 294 },
];

function createPeriodicTable() {
    const table = document.getElementById('periodic-table');
    elements.forEach(element => {
        const elementDiv = document.createElement('div');
        elementDiv.className = 'element';
        elementDiv.innerHTML = `<strong>${element.symbol}</strong><br>${element.name}`;
        elementDiv.onclick = () => showElementInfo(element);
        table.appendChild(elementDiv);
    });
}

function showElementInfo(element) {
    const infoDiv = document.getElementById('element-info');
    infoDiv.innerHTML = `
        <h2>${element.name} (${element.symbol})</h2>
        <p>Atomic Number: ${element.number}</p>
        <p>Atomic Weight: ${element.atomicWeight}</p>
    `;
    infoDiv.classList.remove('hidden');
}

createPeriodicTable();
